#!/usr/bin/env python3
"""Generate broad, compiled Knotwork conformance tests.

The generated file intentionally expands many independent cases into C++ source
so normal build systems, sanitizers, and coverage tools can see each case as
code. Cases exercise binary round trip, validation, flattening, graph queries,
bounds, diagnostics, text export/import, and JSON export.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "tests" / "generated_conformance.cpp"
CASE_COUNT = 520


HEADER = """// Generated by tools/generate_conformance.py. Do not edit by hand.
#include "knotwork/animation.hpp"
#include "knotwork/bounds.hpp"
#include "knotwork/builder.hpp"
#include "knotwork/diagnostics.hpp"
#include "knotwork/flatten.hpp"
#include "knotwork/graph.hpp"
#include "knotwork/json.hpp"
#include "knotwork/query.hpp"
#include "knotwork/text.hpp"

#include <cmath>
#include <iostream>
#include <string>
#include <vector>

namespace knotwork_generated {

struct Failure {
  std::string name;
  std::string message;
};

std::vector<Failure>& failures() {
  static std::vector<Failure> data;
  return data;
}

void check(bool condition, const std::string& name, const std::string& message) {
  if (!condition) {
    failures().push_back({name, message});
  }
}

bool close(float a, float b) {
  return std::fabs(a - b) < 0.001f;
}

}  // namespace knotwork_generated

"""


def case_source(i: int) -> str:
    root_x = i % 17
    mesh_x = (i % 11) + 1
    mesh_y = (i % 7) * 0.25
    inst_x = -((i % 13) + 1)
    light_y = (i % 9) + 2
    scale = 1.0 + (i % 5) * 0.1
    roughness = 0.2 + (i % 6) * 0.1
    metallic = (i % 4) * 0.05
    expected_mesh_x = root_x + mesh_x
    expected_instance_x = root_x + inst_x + root_x + mesh_x
    return f"""
void generated_case_{i:04d}() {{
  using namespace knotwork;
  const std::string name = "generated_case_{i:04d}";
  SceneBuilder builder;
  const std::uint32_t mat = builder.add_material("mat_{i}", {{{(i % 3) / 2.0:.3f}f, {(i % 5) / 4.0:.3f}f, {(i % 7) / 6.0:.3f}f}}, {roughness:.3f}f, {metallic:.3f}f);
  const std::uint32_t root = builder.add_node("root_{i}", NodeKind::Empty, kNoIndex, translated({root_x:.3f}f, 0.0f, 0.0f));
  const std::uint32_t mesh = builder.add_mesh("mesh_{i}", root, mat, trs({{{mesh_x:.3f}f, {mesh_y:.3f}f, 0.0f}}, {{}}, {{{scale:.3f}f, {scale:.3f}f, {scale:.3f}f}}));
  const std::uint32_t camera = builder.add_camera("camera_{i}", root, {45 + (i % 30):.3f}f, translated(0.0f, 2.0f, {4 + (i % 6):.3f}f));
  const std::uint32_t light = builder.add_light("light_{i}", root, LightKind::Point, {1 + (i % 20):.3f}f, translated(0.0f, {light_y:.3f}f, 1.0f));
  const std::uint32_t inst = builder.add_instance("copy_{i}", root, mesh, translated({inst_x:.3f}f, 0.0f, 0.0f));
  Scene scene = builder.take();
  auto loaded = load_scene(save_scene(scene));
  knotwork_generated::check(loaded.ok(), name, loaded.ok() ? "" : loaded.error().message);
  if (!loaded.ok()) return;
  auto flattened = flatten_scene(loaded.value());
  knotwork_generated::check(flattened.ok(), name, flattened.ok() ? "" : flattened.error().message);
  if (!flattened.ok()) return;
  knotwork_generated::check(knotwork_generated::close(flattened.value()[mesh].world.at(0, 3), {expected_mesh_x:.3f}f), name, "mesh world x mismatch");
  knotwork_generated::check(knotwork_generated::close(flattened.value()[inst].world.at(0, 3), {expected_instance_x:.3f}f), name, "instance world x mismatch");
  knotwork_generated::check(root_nodes(loaded.value()).size() == 1, name, "root count mismatch");
  knotwork_generated::check(child_nodes(loaded.value(), root).size() == 4, name, "child count mismatch");
  knotwork_generated::check(descendants(loaded.value(), root).size() == 4, name, "descendant count mismatch");
  auto path = path_to_node(loaded.value(), inst);
  knotwork_generated::check(path && path->display.find("copy_{i}") != std::string::npos, name, "path did not contain instance name");
  NodeQuery mesh_query;
  mesh_query.kind = NodeKind::Mesh;
  knotwork_generated::check(query_nodes(loaded.value(), mesh_query).size() == 1, name, "mesh query mismatch");
  NodeQuery leaf_query;
  leaf_query.leaves_only = true;
  knotwork_generated::check(query_nodes(loaded.value(), leaf_query).size() == 4, name, "leaf query mismatch");
  auto local_bounds = default_unit_mesh_bounds(loaded.value());
  auto bounds = scene_bounds(loaded.value(), local_bounds);
  knotwork_generated::check(bounds.has_value(), name, "missing scene bounds");
  knotwork_generated::check(bounds && bounds->contains({{{expected_mesh_x:.3f}f, {mesh_y:.3f}f, 0.0f}}), name, "bounds do not contain mesh point");
  AnimationClip clip;
  clip.name = "clip_{i}";
  clip.duration = 2.0f;
  clip.tracks.push_back(NodeTrack{{mesh, {{{{0.0f, translated({mesh_x:.3f}f, 0.0f, 0.0f), Interpolation::Linear}}, {{2.0f, translated({mesh_x + 2:.3f}f, 0.0f, 0.0f), Interpolation::Linear}}}}}});
  knotwork_generated::check(validate_clip(loaded.value(), clip).code == SceneErrorCode::None, name, "clip validation failed");
  Scene animated = apply_clip(loaded.value(), clip, 1.0f);
  auto animated_flat = flatten_scene(animated);
  knotwork_generated::check(animated_flat.ok(), name, "animated flatten failed");
  knotwork_generated::check(animated_flat.ok() && knotwork_generated::close(animated_flat.value()[mesh].world.at(0, 3), {expected_mesh_x + 1:.3f}f), name, "animated mesh x mismatch");
  auto diagnostics = diagnose_scene(loaded.value());
  std::string formatted = format_diagnostics(loaded.value(), diagnostics);
  knotwork_generated::check(formatted.find("error") == std::string::npos, name, "diagnostics contained an error");
  std::string text = scene_to_text(loaded.value());
  auto from_text = scene_from_text(text);
  knotwork_generated::check(from_text.ok(), name, from_text.ok() ? "" : from_text.error().message);
  std::string json = scene_to_json(loaded.value());
  knotwork_generated::check(json.find("\\\"nodes\\\"") != std::string::npos, name, "json missing nodes");
  (void)camera;
  (void)light;
}}
"""


def main() -> None:
    chunks = [HEADER]
    for i in range(CASE_COUNT):
        chunks.append(case_source(i))
    chunks.append("\nnamespace knotwork_generated {\n\n")
    chunks.append("int run_generated_conformance() {\n")
    for i in range(CASE_COUNT):
        chunks.append(f"  generated_case_{i:04d}();\n")
    chunks.append("""  if (!failures().empty()) {
    for (const Failure& failure : failures()) {
      std::cerr << failure.name << ": " << failure.message << "\\n";
    }
    return 1;
  }
  return 0;
}

}  // namespace knotwork_generated
""")
    OUT.write_text("".join(chunks), encoding="utf-8")


if __name__ == "__main__":
    main()
